r"""The LaTeX scaffolding: preamble, title page, and front-matter header.

These are filled by `document.fill` with `<<KEY>>` placeholders (not str.format, because LaTeX is
full of literal braces). The custom macros defined here are what `document.py` emits per entry:
\bookgroup (letter band), \entryhead (headword + anchor + bookmark), \webheading (run-in
subheading), the `plainterms` aside, the `seealso` list, and \entryline (List of Entries row).
"""

# Text-font presets. Each maps to (pdflatex package line, xelatex/lualatex \setmainfont line).
# All are libre faces shipped with TeX Live / MacTeX. Under Unicode engines the faces are loaded
# *by file* (the TeX Gyre / XCharter OTFs live in texmf, not in the OS font registry, so loading
# them by family name fails). Maths stays Latin Modern / Computer Modern (the few inline symbols),
# which pairs cleanly with any of these. `default` = Latin Modern.
def _otf(stem, up="regular", it="italic", bf="bold", bi="bolditalic"):
    return (r"\setmainfont{%s}[Extension=.otf, UprightFont=*-%s, ItalicFont=*-%s, "
            r"BoldFont=*-%s, BoldItalicFont=*-%s]" % (stem, up, it, bf, bi))


FONTS = {
    "default":  (r"\usepackage{lmodern}",   r""),                       # Latin Modern
    "bookman":  (r"\usepackage{tgbonum}",   _otf("texgyrebonum")),      # Bookman Old Style
    "palatino": (r"\usepackage{tgpagella}", _otf("texgyrepagella")),    # Palatino
    "times":    (r"\usepackage{tgtermes}",  _otf("texgyretermes")),     # Times
    "charter":  (r"\usepackage{XCharter}",
                 _otf("XCharter", "Roman", "Italic", "Bold", "BoldItalic")),
}


PREAMBLE = r"""% Generated by scripts/book.py — do not edit by hand; re-run the script.
\documentclass[11pt,<<SIDES>>]{book}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  <<FONT_PDFTEX>>
\else
  \usepackage{fontspec}
  <<FONT_UNICODE>>
\fi
\usepackage{amsmath,amssymb}
\usepackage{newunicodechar}
\usepackage[<<PAPER>>,margin=<<MARGIN>>]{geometry}
\usepackage{xcolor}
\usepackage{microtype}
\usepackage{multicol}
\usepackage{enumitem}
\usepackage{needspace}
\usepackage[most]{tcolorbox}
\usepackage{fancyhdr}
\usepackage{truncate}
\usepackage{etoolbox}
\usepackage{hyperref}
\usepackage{bookmark}

% --- portable Unicode: every glyph the corpus uses, mapped to engine-agnostic LaTeX ---
<<UNICODE>>

% --- palette ---
\definecolor{refcolor}{RGB}{120,28,32}
\definecolor{rulecolor}{RGB}{170,170,170}
\definecolor{asidebg}{RGB}{244,242,236}
\definecolor{asideline}{RGB}{193,158,103}
\hypersetup{colorlinks=true, linkcolor=refcolor, urlcolor=refcolor, citecolor=refcolor,
  breaklinks=true, pdftitle={<<TITLE>>}, pdfauthor={philosophy web}, bookmarksnumbered=false}
\setcounter{tocdepth}{1}

% --- two-column feel: a thin rule between the columns ---
\setlength{\columnseprule}{<<COLSEPRULE>>}
\renewcommand{\columnseprulecolor}{\color{rulecolor}}
\setlength{\columnsep}{1.6em}
\raggedbottom
\setlist{leftmargin=1.3em, itemsep=2pt, topsep=3pt, parsep=0pt}

% --- running head: book title (verso) and current entry as a guide word (recto) ---
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0.3pt}
% long argument/claim headwords are truncated at a word boundary (…) so the guide word fits
\fancyhead[LE]{\small\scshape <<RUNHEAD>>}
\fancyhead[RO]{\small\scshape\truncate{0.7\headwidth}{\rightmark}}
\fancyhead[LO,RE]{\small\thepage}
\fancypagestyle{plain}{\fancyhf{}\renewcommand{\headrulewidth}{0pt}\fancyfoot[C]{\small\thepage}}

% --- letter / group divider: full-width band on a fresh page ---
\newcommand{\bookgroup}[1]{%
  \clearpage
  \phantomsection\addcontentsline{toc}{chapter}{#1}%
  \begin{center}\rule{0.5\linewidth}{0.4pt}\\[4pt]
    {\Huge\bfseries #1}\\[3pt]\rule{0.5\linewidth}{0.4pt}\end{center}
  \vspace{0.6\baselineskip}\markboth{#1}{#1}}

% --- type glyph: a small, dimmed mark of the entry's kind (its LaTeX comes from glyphs.py) ---
\newcommand{\entryglyph}[1]{{\normalfont\footnotesize\color{black!45}#1}}

% --- an entry: anchor + PDF bookmark + headword + optional subtitle + etiquette line ---
% #1 anchor id · #2 rich headword (body + ToC) · #3 etiquette · #4 plain guide word (mark) ·
% #5 subtitle (the full title when it differs from the headword; empty = omitted) · #6 type glyph
\newcommand{\entryhead}[6]{%
  \par\addvspace{0.9\baselineskip}\needspace{4\baselineskip}%
  \phantomsection\label{entry:#1}\addcontentsline{toc}{section}{#2}%
  \markright{#4}%
  {\raggedright\large\bfseries\entryglyph{#6}\hspace{0.4em}#2\par}%
  \ifstrempty{#5}{}{{\nopagebreak\smallskip\raggedright\itshape\small\color{black!75} #5\par}}%
  {\nopagebreak\smallskip\footnotesize\itshape\color{black!65} #3\par}%
  \nopagebreak\vspace{2pt}}

% --- a `### subheading` within an entry: small-caps run-in ---
\newcommand{\webheading}[1]{\par\addvspace{5pt}\noindent{\normalfont\scshape #1}\par\nopagebreak\smallskip}

% --- `### In plain terms` -> shaded aside that can break across columns/pages ---
\newtcolorbox{plainterms}{breakable, enhanced, boxrule=0pt, frame hidden,
  colback=asidebg, borderline west={2pt}{0pt}{asideline},
  left=8pt, right=6pt, top=5pt, bottom=5pt, before skip=7pt, after skip=7pt,
  fontupper=\small}

% --- `### See also` list ---
\newlist{seealso}{itemize}{1}
\setlist[seealso]{label=\textcolor{refcolor}{\small$\triangleright$}, leftmargin=1.4em,
  itemsep=2pt, topsep=2pt, parsep=0pt}

% --- front matter: the Symbols key (a small list-of-abbreviations section) ---
% #1 = glyph (full strength, legible) · #2 = type name
\newcommand{\symbolkeyheading}{\thispagestyle{plain}\markboth{}{}%
  \vspace*{1.2\baselineskip}{\centering\Large\bfseries Symbols\par}\vspace{0.8\baselineskip}%
  \begingroup\centering}
\newcommand{\symbolkeyitem}[2]{\makebox[1.5em][c]{#1}\,\,#2\par\smallskip}
\newcommand{\symbolkeyend}{\endgroup\clearpage}

% --- front matter: a List of Entries row (#1 type glyph · #2 anchor id · #3 name) ---
\newcommand{\entryline}[3]{\noindent\makebox[1.5em][l]{\entryglyph{#1}}%
  \hyperref[entry:#2]{#3}\,\dotfill\,\pageref{entry:#2}\par}
\newenvironment{listofentries}{\footnotesize\begin{multicols}{2}\raggedright\setlength{\parskip}{2pt}}
  {\end{multicols}\clearpage}

% --- back matter: Sources (bibliography of every cited source, hanging indent) ---
\newcommand{\sourcesband}{%
  \clearpage
  \phantomsection\addcontentsline{toc}{chapter}{Sources}%
  \begin{center}\rule{0.5\linewidth}{0.4pt}\\[4pt]
    {\Huge\bfseries Sources}\\[3pt]\rule{0.5\linewidth}{0.4pt}\end{center}
  \vspace{0.6\baselineskip}\markboth{Sources}{Sources}}
\newenvironment{sourcelist}{\small\setlength{\parindent}{0pt}\raggedright\sloppy}{\par}
% #1 = anchor id (empty for a second/third work under the same source node) · #2 = the reference
\newcommand{\sourceitem}[2]{%
  \par\addvspace{3pt}\ifstrempty{#1}{}{\phantomsection\label{source:#1}}%
  \hangindent=1.5em\hangafter=1 #2\par}
"""

TITLEPAGE = r"""\thispagestyle{empty}
\begin{titlepage}\centering
  \vspace*{0.20\textheight}
  {\Huge\bfseries <<TITLE>>\par}
  \vspace{1.2\baselineskip}
  {\large\itshape <<SUBTITLE>>\par}
  \vfill
  {\small <<DATE>>\par}
\end{titlepage}"""

FRONT = r"""\markboth{}{}\thispagestyle{plain}
\vspace*{1.2\baselineskip}
{\centering\Large\bfseries List of Entries\par}
{\centering\small <<COUNT>> entries \,\textperiodcentered\, <<DATE>>\par}
\vspace{1\baselineskip}"""
