r"""The LaTeX scaffolding: preamble, title page, and front-matter header.

These are filled by `document.fill` with `<<KEY>>` placeholders (not str.format, because LaTeX is
full of literal braces). The custom macros defined here are what `document.py` emits per entry:
\bookgroup (letter band), \entryhead (headword + anchor + bookmark), \webheading (run-in
subheading), the `plainterms` aside, the `seealso` list, and \entryline (List of Entries row).
"""

PREAMBLE = r"""% Generated by scripts/book.py — do not edit by hand; re-run the script.
\documentclass[11pt,<<SIDES>>]{book}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{lmodern}
\else
  \usepackage{fontspec}
\fi
\usepackage{amsmath,amssymb}
\usepackage{newunicodechar}
\usepackage[<<PAPER>>,margin=<<MARGIN>>]{geometry}
\usepackage{xcolor}
\usepackage{microtype}
\usepackage{multicol}
\usepackage{enumitem}
\usepackage{needspace}
\usepackage[most]{tcolorbox}
\usepackage{fancyhdr}
\usepackage{truncate}
\usepackage{hyperref}
\usepackage{bookmark}

% --- portable Unicode: every glyph the corpus uses, mapped to engine-agnostic LaTeX ---
<<UNICODE>>

% --- palette ---
\definecolor{refcolor}{RGB}{120,28,32}
\definecolor{rulecolor}{RGB}{170,170,170}
\definecolor{asidebg}{RGB}{244,242,236}
\definecolor{asideline}{RGB}{193,158,103}
\hypersetup{colorlinks=true, linkcolor=refcolor, urlcolor=refcolor, citecolor=refcolor,
  breaklinks=true, pdftitle={<<TITLE>>}, pdfauthor={philosophy web}, bookmarksnumbered=false}
\setcounter{tocdepth}{1}

% --- two-column feel: a thin rule between the columns ---
\setlength{\columnseprule}{<<COLSEPRULE>>}
\renewcommand{\columnseprulecolor}{\color{rulecolor}}
\setlength{\columnsep}{1.6em}
\raggedbottom
\setlist{leftmargin=1.3em, itemsep=2pt, topsep=3pt, parsep=0pt}

% --- running head: book title (verso) and current entry as a guide word (recto) ---
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0.3pt}
% long argument/claim headwords are truncated at a word boundary (…) so the guide word fits
\fancyhead[LE]{\small\scshape <<RUNHEAD>>}
\fancyhead[RO]{\small\scshape\truncate{0.7\headwidth}{\rightmark}}
\fancyhead[LO,RE]{\small\thepage}
\fancypagestyle{plain}{\fancyhf{}\renewcommand{\headrulewidth}{0pt}\fancyfoot[C]{\small\thepage}}

% --- letter / group divider: full-width band on a fresh page ---
\newcommand{\bookgroup}[1]{%
  \clearpage
  \phantomsection\addcontentsline{toc}{chapter}{#1}%
  \begin{center}\rule{0.5\linewidth}{0.4pt}\\[4pt]
    {\Huge\bfseries #1}\\[3pt]\rule{0.5\linewidth}{0.4pt}\end{center}
  \vspace{0.6\baselineskip}\markboth{#1}{#1}}

% --- an entry: anchor + PDF bookmark + headword + etiquette line ---
% #1 anchor id · #2 rich headword (body + ToC) · #3 etiquette · #4 plain guide word (mark)
\newcommand{\entryhead}[4]{%
  \par\addvspace{0.9\baselineskip}\needspace{4\baselineskip}%
  \phantomsection\label{entry:#1}\addcontentsline{toc}{section}{#2}%
  \markright{#4}%
  {\raggedright\normalfont\large\bfseries #2\par}%
  {\nopagebreak\smallskip\footnotesize\itshape\color{black!65} #3\par}%
  \nopagebreak\vspace{2pt}}

% --- a `### subheading` within an entry: small-caps run-in ---
\newcommand{\webheading}[1]{\par\addvspace{5pt}\noindent{\normalfont\scshape #1}\par\nopagebreak\smallskip}

% --- `### In plain terms` -> shaded aside that can break across columns/pages ---
\newtcolorbox{plainterms}{breakable, enhanced, boxrule=0pt, frame hidden,
  colback=asidebg, borderline west={2pt}{0pt}{asideline},
  left=8pt, right=6pt, top=5pt, bottom=5pt, before skip=7pt, after skip=7pt,
  fontupper=\small}

% --- `### See also` list ---
\newlist{seealso}{itemize}{1}
\setlist[seealso]{label=\textcolor{refcolor}{\small$\triangleright$}, leftmargin=1.4em,
  itemsep=2pt, topsep=2pt, parsep=0pt}

% --- front matter: a List of Entries row ---
\newcommand{\entryline}[2]{\noindent\hyperref[entry:#1]{#2}\,\dotfill\,\pageref{entry:#1}\par}
\newenvironment{listofentries}{\footnotesize\begin{multicols}{2}\raggedright\setlength{\parskip}{2pt}}
  {\end{multicols}\clearpage}
"""

TITLEPAGE = r"""\thispagestyle{empty}
\begin{titlepage}\centering
  \vspace*{0.20\textheight}
  {\Huge\bfseries <<TITLE>>\par}
  \vspace{1.2\baselineskip}
  {\large\itshape <<SUBTITLE>>\par}
  \vfill
  {\small <<DATE>>\par}
\end{titlepage}"""

FRONT = r"""\markboth{}{}\thispagestyle{plain}
\vspace*{1.2\baselineskip}
{\centering\Large\bfseries List of Entries\par}
{\centering\small <<COUNT>> entries \,\textperiodcentered\, <<DATE>>\par}
\vspace{1\baselineskip}"""
